services:
  - type: web
    name: ters-kose
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    autoDeployTrigger: commit
